-- Base schema for MoodBuds
-- Contains core tables

CREATE TABLE admin_roles (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, description VARCHAR(255), is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE admin_permissions (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, permission_key VARCHAR(100) NOT NULL UNIQUE, module VARCHAR(50) NOT NULL, description VARCHAR(255));

CREATE TABLE admin_users (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, role_id INT UNSIGNED NOT NULL, email VARCHAR(255) UNIQUE, password_hash VARCHAR(255) NOT NULL, full_name VARCHAR(200) NOT NULL, mobile VARCHAR(15), is_active TINYINT NOT NULL DEFAULT 1, require_2fa TINYINT NOT NULL DEFAULT 0, last_login_at DATETIME, failed_attempts TINYINT NOT NULL DEFAULT 0, locked_until DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY fk_admin_users_role (role_id), CONSTRAINT fk_admin_users_role FOREIGN KEY (role_id) REFERENCES admin_roles (id));

CREATE TABLE admin_role_permissions (role_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, PRIMARY KEY (role_id, permission_id), KEY fk_arp_permission (permission_id), CONSTRAINT fk_arp_permission FOREIGN KEY (permission_id) REFERENCES admin_permissions (id) ON DELETE CASCADE, CONSTRAINT fk_arp_role FOREIGN KEY (role_id) REFERENCES admin_roles (id) ON DELETE CASCADE);

CREATE TABLE users (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255), mobile VARCHAR(15) UNIQUE, mobile_verified TINYINT NOT NULL DEFAULT 0, email_verified TINYINT NOT NULL DEFAULT 0, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL DEFAULT '', date_of_birth DATE, gender VARCHAR(20) NOT NULL DEFAULT 'UNSPECIFIED', referral_code VARCHAR(20) UNIQUE, referred_by BIGINT UNSIGNED, is_active TINYINT NOT NULL DEFAULT 1, failed_login_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0, locked_until DATETIME NULL, last_login_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_users_mobile_verified (mobile_verified), KEY idx_users_is_active (is_active), KEY fk_users_referred_by (referred_by), CONSTRAINT fk_users_referred_by FOREIGN KEY (referred_by) REFERENCES users (id) ON DELETE SET NULL);

CREATE TABLE categories (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_categories_active (is_active));

CREATE TABLE subcategories (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, category_id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_subcategories_category (category_id), CONSTRAINT fk_subcategories_category FOREIGN KEY (category_id) REFERENCES categories (id));

CREATE TABLE moods (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, slug VARCHAR(100), emoji VARCHAR(10), tagline VARCHAR(255), personality_tagline VARCHAR(255), color VARCHAR(7), banner_image_url VARCHAR(500), banner_image_path VARCHAR(500), display_order INT, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE gst_rates (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, rate_name VARCHAR(50) NOT NULL, gst_percentage DECIMAL(5,2) NOT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE products (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, sku VARCHAR(50) NOT NULL UNIQUE, slug VARCHAR(100), name VARCHAR(255) NOT NULL, description LONGTEXT, fabric_details VARCHAR(255), color_name VARCHAR(100), category_id INT NOT NULL, subcategory_id INT NOT NULL, gst_rate_id INT, price INT NOT NULL, discount_price INT, is_active TINYINT NOT NULL DEFAULT 1, is_featured TINYINT NOT NULL DEFAULT 0, is_new_arrival TINYINT NOT NULL DEFAULT 0, is_best_seller TINYINT NOT NULL DEFAULT 0, publication_status VARCHAR(50) DEFAULT 'DRAFT', return_window_days INT DEFAULT 7, created_by INT UNSIGNED, updated_by INT UNSIGNED, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_products_category (category_id), KEY idx_products_subcategory (subcategory_id), KEY fk_products_gst (gst_rate_id), CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id), CONSTRAINT fk_products_subcategory FOREIGN KEY (subcategory_id) REFERENCES subcategories (id), CONSTRAINT fk_products_gst FOREIGN KEY (gst_rate_id) REFERENCES gst_rates (id));

CREATE TABLE product_sizes (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, product_id BIGINT NOT NULL, size VARCHAR(10) NOT NULL, stock_quantity INT NOT NULL DEFAULT 0, low_stock_threshold INT NOT NULL DEFAULT 10, is_available TINYINT NOT NULL DEFAULT 1, UNIQUE KEY uq_product_size (product_id, size), CONSTRAINT fk_product_sizes_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE);

CREATE TABLE product_images (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, product_id BIGINT NOT NULL, image_url VARCHAR(500) NOT NULL, is_primary TINYINT NOT NULL DEFAULT 0, KEY idx_product_images_product (product_id), CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE);

CREATE TABLE product_mood_tags (product_id BIGINT NOT NULL, mood_id INT NOT NULL, PRIMARY KEY (product_id, mood_id), KEY idx_pmt_mood (mood_id), CONSTRAINT fk_pmt_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE, CONSTRAINT fk_pmt_mood FOREIGN KEY (mood_id) REFERENCES moods (id) ON DELETE CASCADE);

CREATE TABLE carts (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED, coupon_id BIGINT, coupon_discount INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_carts_user (user_id), CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE cart_items (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, cart_id BIGINT NOT NULL, product_id BIGINT NOT NULL, size VARCHAR(10) NOT NULL, quantity SMALLINT NOT NULL DEFAULT 1, unit_price INT NOT NULL, unit_discount_price INT, UNIQUE KEY uq_cart_product_size (cart_id, product_id, size), KEY idx_cart_items_cart (cart_id), KEY fk_cart_items_product (product_id), CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE, CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id));

CREATE TABLE orders (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'PENDING_PAYMENT', total_amount INT NOT NULL, shipping_cost INT NOT NULL DEFAULT 0, payment_method VARCHAR(50), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_orders_user (user_id), KEY idx_orders_status (status), CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id));

CREATE TABLE order_items (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, product_snapshot JSON, size VARCHAR(10), quantity INT NOT NULL, unit_price INT NOT NULL, unit_discount_price INT, line_total INT NOT NULL, KEY idx_order_items_order (order_id), CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE);

CREATE TABLE order_status_history (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, order_id BIGINT NOT NULL, old_status VARCHAR(50), new_status VARCHAR(50) NOT NULL, changed_by INT, reason VARCHAR(500), changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_order_status_history_order (order_id), CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE);

CREATE TABLE payments (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, order_id BIGINT NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'INITIATED', method VARCHAR(50), amount INT NOT NULL, currency CHAR(3) DEFAULT 'INR', gateway_order_id VARCHAR(100), gateway_payment_id VARCHAR(100), gateway_fee INT, gateway_response JSON, initiated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_payments_order (order_id), KEY idx_payments_status (status), CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id));

CREATE TABLE return_requests (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'INITIATED', reason VARCHAR(500), pickup_address_id BIGINT, images JSON, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_return_requests_user (user_id), CONSTRAINT fk_return_requests_user FOREIGN KEY (user_id) REFERENCES users (id));

CREATE TABLE return_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, return_request_id BIGINT NOT NULL, order_item_id BIGINT NOT NULL, refund_amount INT NOT NULL, KEY idx_return_items_request (return_request_id), CONSTRAINT fk_return_items_request FOREIGN KEY (return_request_id) REFERENCES return_requests (id) ON DELETE CASCADE);

CREATE TABLE refunds (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, return_request_id BIGINT NOT NULL, amount INT NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'INITIATED', gateway_refund_id VARCHAR(100), gateway_response JSON, initiated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_refunds_return_request FOREIGN KEY (return_request_id) REFERENCES return_requests (id) ON DELETE CASCADE);

CREATE TABLE coupons (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, description VARCHAR(500), type VARCHAR(50) NOT NULL, discount_value DECIMAL(10,2) NOT NULL, min_order_value INT, max_discount_amount INT, usage_limit_global INT, usage_limit_per_user INT, current_usage_count INT NOT NULL DEFAULT 0, is_active TINYINT NOT NULL DEFAULT 1, is_public TINYINT NOT NULL DEFAULT 1, valid_from DATETIME, valid_until DATETIME, created_by INT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_coupons_active (is_active));

CREATE TABLE quiz_paths (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(500), is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE quiz_questions (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, path_id BIGINT NOT NULL, question_text VARCHAR(500) NOT NULL, question_order INT NOT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_quiz_questions_path (path_id), CONSTRAINT fk_quiz_questions_path FOREIGN KEY (path_id) REFERENCES quiz_paths (id) ON DELETE CASCADE);

CREATE TABLE quiz_options (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, question_id BIGINT NOT NULL, option_text VARCHAR(255) NOT NULL, option_order INT NOT NULL, mood_id INT, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_quiz_options_question (question_id), CONSTRAINT fk_quiz_options_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE);

CREATE TABLE quiz_sessions (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, path_id BIGINT NOT NULL, responses JSON, started_at DATETIME, is_completed TINYINT NOT NULL DEFAULT 0, completed_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_quiz_sessions_user (user_id), CONSTRAINT fk_quiz_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE quiz_session_answers (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, quiz_session_id BIGINT NOT NULL, question_id BIGINT NOT NULL, selected_option_id BIGINT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_quiz_session_answers_session (quiz_session_id), KEY idx_quiz_session_answers_question (question_id), CONSTRAINT fk_quiz_session_answers_session FOREIGN KEY (quiz_session_id) REFERENCES quiz_sessions (id) ON DELETE CASCADE, CONSTRAINT fk_quiz_session_answers_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id));

CREATE TABLE wishlists (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL UNIQUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_wishlists_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE wishlist_items (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, wishlist_id BIGINT NOT NULL, product_id BIGINT NOT NULL, size VARCHAR(10), added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_wishlist_items_wishlist (wishlist_id), KEY idx_wishlist_items_product (product_id), CONSTRAINT fk_wishlist_items_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists (id) ON DELETE CASCADE, CONSTRAINT fk_wishlist_items_product FOREIGN KEY (product_id) REFERENCES products (id));

CREATE TABLE gst_invoices (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, order_id BIGINT NOT NULL, invoice_number VARCHAR(50) NOT NULL UNIQUE, invoice_date DATETIME NOT NULL, subtotal_amount INT NOT NULL, gst_amount INT NOT NULL, total_amount INT NOT NULL, KEY idx_gst_invoices_order (order_id), CONSTRAINT fk_gst_invoices_order FOREIGN KEY (order_id) REFERENCES orders (id));

CREATE TABLE inventory_logs (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, product_id BIGINT NOT NULL, size VARCHAR(10), transaction_type VARCHAR(50) NOT NULL, quantity_change INT NOT NULL, old_quantity INT, new_quantity INT, reference_id VARCHAR(100), notes VARCHAR(500), created_by INT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_inventory_logs_product (product_id), CONSTRAINT fk_inventory_logs_product FOREIGN KEY (product_id) REFERENCES products (id));

CREATE TABLE otp_verifications (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, mobile VARCHAR(15) NOT NULL, otp_code VARCHAR(10) NOT NULL, attempts INT NOT NULL DEFAULT 0, expires_at DATETIME NOT NULL, verified_at DATETIME, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE size_charts (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, product_id BIGINT, subcategory_id INT, size_name VARCHAR(20) NOT NULL, description VARCHAR(255), measurement_image_url VARCHAR(500));

CREATE TABLE admin_activity_logs (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, admin_user_id INT UNSIGNED NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id VARCHAR(50) NOT NULL, old_value JSON, new_value JSON, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_aal_admin_user (admin_user_id), KEY idx_aal_entity (entity_type, entity_id), KEY idx_aal_created_at (created_at), CONSTRAINT fk_aal_admin_user FOREIGN KEY (admin_user_id) REFERENCES admin_users (id));

CREATE TABLE customer_auth_sessions (id CHAR(36) NOT NULL PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, refresh_token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, last_used_at DATETIME NULL, KEY idx_customer_auth_sessions_user (user_id), KEY idx_customer_auth_sessions_expiry (expires_at), CONSTRAINT fk_customer_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE social_links (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(50) NOT NULL, url VARCHAR(500) NOT NULL, icon_class VARCHAR(100), display_order INT, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_social_links_active (is_active));

CREATE TABLE site_content (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, page_key VARCHAR(100) NOT NULL UNIQUE, section_key VARCHAR(100) NOT NULL, content_html LONGTEXT, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by INT);
